### PR TITLE
Repository records - additional access points and facets.

### PR DESCRIPTION
**Pull request by sbreker**
Currently in 2.0, when browsing archival institutions there are facets for:
- archive type
- region (i.e. province in the Canadian context)

This enhancement would add two access points to the ISDIAH record:
- geographic subregion (e.g., Southwestern Saskatchewan, Northern Saskatchewan)
- thematic area (e.g., Agriculture, Local/regional history, Aboriginal peoples)

...and add facets to the repository browse:
- locality (city/community)
- geographic subregion
- thematic area

Default thematic areas are created for new installs and migrations.

### CODE REVIEW

**Comment by fiver-watson** [comment]
Steve, thanks! This is really exciting. Looking forward to testing it out! 

Developers - you can relate this to the following issue ticket when merging the pull request: https://projects.artefactual.com/issues/5596

And mark that issue as QA/Review when it is in 2.x and ready for testing, please.

**Comment by sevein** [comment]
@sbreker, @fiver-watson is going to test your branch locally but we are planning to merge this into qa/2.1.x ASAP. Note that our 2.x branch was removed in favour of qa/2.1.x and this PR was closed by github as an unexpected side effect, but we'll still process it even if it's closed.

**Comment by sbreker** [comment]
Thanks for the info!   Let me know if you have any questions regarding the change.

Steve

**Comment by sevein** [comment]
Merged, chapeau! The only little detail that you missed was to bump the database version in settings.yml for newcomers. Thank you so much!

**Pull request closed without merging**
