### PR TITLE
Fix Filters button display toggle on small screens, refs #11004

### PR DESCRIPTION
**Pull request by g011um**
Fix Filters button display toggle on small screens, refs #11004

### CODE REVIEW

**Comment by fiver-watson** [comment]
Hi Darryl, 

Thanks for this fix! Do we have a signed Contributor's Agreement from you yet? Please see the following for more information and a copy - we'll need a signed copy to be able to merge your fix to the public release: 

* https://wiki.accesstomemory.org/Development/Contribute_code

Thanks!

**Comment by g011um** [comment]
Dan, I've just printed it, signed it, and sent it off to the email address suggested.  Thanks for the reminder.

**Comment by fiver-watson** [comment]
Thank you @g011um ! I've received it, and we've assigned a developer to take a look at this soon.

**Comment by sbreker** [comment]
PR looks great Darryl - Good catch! I have merged your fix into qa/2.4.x and also backported it into stable/2.3.x as this same issue affects that release.

You might notice I've updated your commit message a bit. We try to keep the first line of the message as a descriptive title <= 50 chars, followed by a blank line, followed by a brief description of the change wrapping at 80 chars.

You can view your merged commit here: https://github.com/artefactual/atom/commit/71c876a8777dbe57d99e62d162e5774f58b8fb09

Thanks for the contribution!  --Steve

**Comment by fiver-watson** [comment]
I've also added you to our contributors page! 

* https://wiki.accesstomemory.org/Community/Contributors

Thanks again - I will try to QA this soon :)

**Comment by g011um** [comment]
I'm famous now!

**Pull request closed without merging**
