### PR TITLE
Fix inherited creators on ES IO save, refs #11788

### PR DESCRIPTION
**Pull request by jraddaoui**
Inherited creators were only being considered if sent as part of the
options, which is the case in the entire collection population but
it isn't in individual updates.

### CODE REVIEW

**Comment by jraddaoui** [comment]
I'll cherry-pick to stable/2.4.x when reviewed.

**Comment by jraddaoui** [comment]
Needed in #684

**Review by sbreker — APPROVED** [review]

**Comment by sbreker** [comment]
Looks good!

**Comment by jraddaoui** [comment]
5f19171 in stable/2.4.x

**Pull request merged**
