### PR TITLE
Multicultural Varnish cache support, refs #13389

### PR DESCRIPTION
**Pull request by mcantelon**
Changes to allow, with the correct Varnish configuration, content to be
cached in non-default cultures.

### CODE REVIEW

**Review by jraddaoui — COMMENTED** [review]
Thanks @mcantelon,

I didn't know about that event and the code changes look really good. I wonder what is the configuration needed in Varnish to make this work. Would you need to allow the set-cookie header in the responses to requests using the `sf_culture` parameter? And then, would you use the `HTTP_X_ATOM_CULTURE` request header to generate the cache hash based on the culture? How is that header sent on each request?

**Comment by mcantelon** [comment]
Hi @jraddaoui ... here are the VCL changes needed for it to work:

https://projects.artefactual.com/issues/13389#note-3

Basically the Varnish changes do the following:

1. Let requests with `sf_culture` specified as a GET parameter through (to AtoM can set the `atom_culture` cookie)
2. Don't remove `set-cookie` response headers for responses to requests with `sf_culture` set
3. Use the cookie value to set the X-Atom-Culture and incorporate its value into the hash key

**Review by jraddaoui — APPROVED** [review]
Nicely thought @mcantelon, great work!

**Comment by jraddaoui** [comment]
@mcantelon, if it's not a low of work and you're planing to give it a try to https://github.com/artefactual/atom/pull/1160, it would be amazing if you implement those changes in the Varnish config from that PR.

**Comment by jraddaoui** [comment]
Note to self, read ticket updates before review, sorry Mike :P

**Comment by mcantelon** [comment]
@jraddaoui Thanks Radda! I'll give #1160 a try!

**Pull request merged**
