### PR TITLE
Dev/issue 12167 menu locking

### PR DESCRIPTION
**Pull request by mcantelon**
Prevent deletion (adding the myProfile menu: issue 12167) and renaming (11186) of system menus.

### CODE REVIEW

**Review by jraddaoui — CHANGES_REQUESTED** [review]
Looks good @mcantelon, but I wonder, should this two columns default to `true`? They will only be `false` in a few menu items and new ones created by the user should be modificable.

**Comment by mcantelon** [comment]
Good call. I'll make that change.

**Comment by mcantelon** [comment]
I made the change. I ended up rebasing given there are no comments on any lines of code in this PR (so I thought it shouldn't interfere with review).

EDIT: I also added some addition content to the menu YML fixture.

**Review by jraddaoui — APPROVED** [review]
Awesome, thanks @mcantelon!

**Pull request merged**
