### PR TITLE
Remove extraneous ')' in call to get I18n field names, refs #1199

### PR DESCRIPTION
**Pull request by xojc**

### CODE REVIEW

**Comment by fiver-watson** [comment]
Hi @xojc ! Thank you for this contribution - great catch! Our team has already confirmed that this typo causes a 500 error, so we appreciate you finding the cause and submitting this pull request. 

It might seem like overkill for such a small change, but to help protect the open source project and prevent potential disputes over copyright and code ownership later, we ask all contributors to sign a Contributor's Agreement before merging contributions. You can find more information, as well as a copy of the agreement, on our wiki here: 

* https://wiki.accesstomemory.org/Development/Contribute_code#Copyright_and_license
* [here](https://wiki.accesstomemory.org/images/9/9d/Accesstomemory-contributor-agreement-2014.pdf) is a direct link to the agreement as a form-fillable PDF, if you download it and view it in a local PDF reader

You can send this to `agreement@artefactual.com` afterwards - and please let us know if you have any questions!

Additionally: if this seems like way too much work for a single deletion, we understand too. In that case, please let us know - we can close this PR, our developers will make the change, and we can reference you in the commit message if you'd like. 

Thanks again for your contribution to the AtoM project! 

Dan Gillean, MAS, MLIS
AtoM Program Manager
Artefactual Systems

**Comment by xojc** [comment]
Feel free to close this PR, make the change, and I'd love a commit message reference! :-)

**Comment by fiver-watson** [comment]
Ok, thank you @xojc - I've filed the following ticket in our internal issue tracker, so we will close issue #1199 as well. 

Cheers!

**Comment by fiver-watson** [comment]
Oops, here's the ticket: https://projects.artefactual.com/issues/13429

**Comment by fiver-watson** [comment]
FYI @xojc your proposed fix has been merged in https://github.com/artefactual/atom/pull/1204

Thanks again!

**Pull request closed without merging**
