### PR TITLE
Update cookie security settings

### PR DESCRIPTION
**Pull request by anvit**
Use secure and same-site flags for atom cookies.

### CODE REVIEW

**Comment by jraddaoui** [comment]
Nice!

We should make sure this works with Varnish and the example configuration from: https://github.com/artefactual/atom/blob/qa/2.x/docker/etc/varnish/default.vcl

**Comment by jraddaoui** [comment]
Also, what about the `symfony` cookie?

**Comment by anvit** [comment]
> Also, what about the `symfony` cookie?

It's working as expected now! My VM's production config had `session_cookie_secure` set to `false` for some reason but I noticed that that's not the case for the default config. The only thing that's not updated at this point is that the `symfony` cookie doesn't set the same-site flag (likely because symfony 1.4 just didn't have that flag).

**Review by sbreker — APPROVED** [review]
Looks great @anvit! Thanks for adding this!

I was wondering about adding `httponly` to atom_authenticated but I see that this cookie _is_ accessed from AtoM's fullwidthtreeview.js so that setting would not work.

**Pull request merged**
