### PR TITLE
Small spelling fix

### PR DESCRIPTION
**Pull request by misilot**
Adds a space between between "a" and "period"

### CODE REVIEW

**Comment by anvit** [comment]
Hi @misilot ! Thanks for finding and fixing this typo! We'll include this fix in the next AtoM release.

There are a couple things we'd need to do before we can accept this change. The update to `exportAction.class.php` looks good but the message xml files are generated when we run our script for pulling translations, so I would suggest reverting those since those will be fixed automatically (with the appropriate timestamp changes to the translation files) when we run the translations pull from weblate for the next release. 

Also, when you get a chance, would you be able to sign our Contributor Agreement? Here's a link with details about the agreement — https://wiki.accesstomemory.org/Development/Contribute_code#Copyright_and_license

**Comment by misilot** [comment]
Is this a different CLA than already on file with Artefactual?

**Comment by anvit** [comment]
@misilot received, thanks! The only other signed CLA I see is for Archivematica, and we have a separate one for AtoM.

**Review by anvit — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
