### PR TITLE
Fix clipboard send escaping issue, refs #12800

### PR DESCRIPTION
**Pull request by mcantelon**
Fixed escaping-related issue with the clipboard send feature.

### CODE REVIEW

**Review by djjuhasz — COMMENTED** [review]
The new changes look fine to me, but shouldn't the whole thing fail if  `sfConfig::get('app_clipboard_send_url')` is not set?  I can't see how this would work without a destination URL?

**Comment by mcantelon** [comment]
Yeah the "Send" button won't be shown unless `sfConfig::get('app_clipboard_send_url')` is set:

https://github.com/artefactual/atom/blob/qa/2.6.x/apps/qubit/modules/user/templates/clipboardSuccess.php#L55

**Comment by mcantelon** [comment]
I've updated the PR to add a check.

**Review by djjuhasz — APPROVED** [review]
LGTM! 👍

**Pull request merged**
