### PR TITLE
Contact info form translation fix, refs #11602

### PR DESCRIPTION
**Pull request by mcantelon**
Fixed inability to translate labels for a number of fields and text for
several buttons.

### CODE REVIEW

**Review by jraddaoui — APPROVED** [review]
Looks great @mcantelon!! I wouldn't add the 'message.xml' files changes, though. They will be overwritten when we pull from Transifex (or whatever system we may end up using), so no big deal.

**Comment by jraddaoui** [comment]
Actually, don't we need to add labels to the fields without them? E.g.:
https://github.com/artefactual/atom/blob/ebca194d7cc3064f65133b2ef82b03386484beee/apps/qubit/modules/contactinformation/templates/_edit.php#L107

Like it's being done in:
https://github.com/artefactual/atom/blob/ebca194d7cc3064f65133b2ef82b03386484beee/apps/qubit/modules/contactinformation/templates/_edit.php#L127-L129

**Comment by mcantelon** [comment]
Ah, I think you're right. Fixed.

**Comment by jraddaoui** [comment]
Nice, thanks! Looks good!

**Pull request merged**
