### PR TITLE
Web installer and purge task fixes, refs #13051, #13238 and #13290

### PR DESCRIPTION
**Pull request by jraddaoui**
This PR addresses a few issues in the web installer and the purge task:

- af7634f: fixes a regression introduced in qa/2.6.x.
- a3ae9f5 and 772323d: needed in stable/2.5.x too.

I still want (need) to find the reason why removing the transaction filter
reduces the data load time, but the code is ready for review.

### CODE REVIEW

**Comment by jraddaoui** [comment]
Hi @mcantelon, I believe you have been working in part of this lately and I'd appreciate your review.

**Comment by jraddaoui** [comment]
More info about the web installer timeout issue: https://projects.artefactual.com/issues/13051#note-4

**Comment by jraddaoui** [comment]
Hi @mcantelon, I've updated the web installer fix after the latest findings. In the end, splitting the DDL and DML statements in two different request cycles, apart from splitting the data load time, it doesn't require to remove the transaction filter. During the process, I found a problem with the ES configuration management in the web installer, which is addressed in that commit too.

**Comment by mcantelon** [comment]
Thanks @radda! Reviewing this now...

**Review by mcantelon — APPROVED** [review]
Nicely done... good detective work!

The PR looks good to me!

**Comment by jraddaoui** [comment]
Thanks @mcantelon!!

**Pull request merged**
