### PR TITLE
Fix accession counter, refs #11700

### PR DESCRIPTION
**Pull request by mcantelon**
The accession counter, used to create accession identifiers, wasn't being
incremented.

Fixed this by:
* Changing when accession counter is incremented
* Adding an availability check, to avoid identifiers already in use, when
  determining the next accession identifier to use
* Minor refactor to share mask generation code between accessions and
  information objects

### CODE REVIEW

**Review by jraddaoui — COMMENTED** [review]
Hi @mcantelon,

This is looking great but we should put some thinking on this transaction(s).

After this changes, we're getting the value in  `nextAccessionNumber` but incrementing it in `incrementAccessionCounter` (where the transaction happens). Which may lead to race conditions in simultaneous saves.

Moreover, we have a transaction filter that acts on each request and I'm not completely sure how MySQL and Propel work with nested transactions. However we still need to have this transaction for saves that occur outside the request cycle, like in the accession CSV import, or move it to those places.

**Review by jraddaoui — CHANGES_REQUESTED** [review]
It looks like propel ignores nested transactions:

http://propelorm.org/Propel/documentation/06-transactions.html#nested-transactions

So we should be good by moving this transaction to wrap all the operations in `nextAvailableIdentifier`.

**Comment by mcantelon** [comment]
Thanks @jraddaoui ... I've gotten rid of the transaction in the increment function and wrapped the contents of nextAvailableIdentifier in a transaction.

**Review by jraddaoui — APPROVED** [review]
Awesome, thanks @mcantelon!

**Pull request merged**
