### PR TITLE
Improved CSV import with more RAD fields.

### PR DESCRIPTION
**Pull request by seamus-oconnor**

### CODE REVIEW

**Comment by tpantella** [comment]
This implements Cast, Credits, and Signatures as note types that can be imported via CSV import.  It also follows the method used by Language Note for creating these note types if they do not yet exist.

**Comment by sevein** [comment]
@seamus-oconnor, this branch was automatically closed because we have removed our 2.x branch in favour of qa/2.1.x. We are still planning to look at this soon though, thanks!

**Comment by sevein** [comment]
Thanks, @seamus-oconnor. Merged in qa/2.1.x.

**Comment by sevein** [comment]
See also https://projects.artefactual.com/issues/7130

**Pull request closed without merging**
