### PR TITLE
Add a composer test coverage report script

### PR DESCRIPTION
**Pull request by djjuhasz**
Add a `composer test-cov` script that generates a phpunit text format
coverage report (using pcov) and sends it to STDOUT.

### CODE REVIEW

**Review by jraddaoui — APPROVED** [review]
Looks good @djjuhasz!

Maybe we could reference https://projects.artefactual.com/issues/13493 in the commit message and add some notes in https://wiki.accesstomemory.org/wiki/Development/Testing#Unit_tests.

**Comment by djjuhasz** [comment]
@jraddaoui I did this because I didn't know about the documented method of running the [AtoM Unit tests in Docker](https://wiki.accesstomemory.org/wiki/Development/Testing#Docker) using the "ATOM_COVERAGE" environment variable.

After reading the docs, I think it may be better to use the `--coverage-html=.coverage/html` option in the `test-cov` script too. What do you think?

**Comment by jraddaoui** [comment]
I agree @djjuhasz, the text format with that many files is quite long and hard to read. The `ATOM_COVERAGE` env. var was initially added to be able to generate coverage reports from the integration tests, this way is a bit easier so I'd replace the documented method from the Wiki after merging this PR.

Also, I just remembered that we added a coverage section in https://github.com/artefactual/atom/blob/qa/2.x/phpunit.xml#L7-L16 which is already excluding a few directories, so `-dpcov.exclude=\"~vendor~\"` shouldn't be needed (or should replace the vendor entry is you're looking for other vendor directories deep in the tree).

**Comment by djjuhasz** [comment]
https://wiki.accesstomemory.org/wiki/Development/Testing#Docker updated

**Pull request merged**
