### PR TITLE
Add data files for some missing languages

### PR DESCRIPTION
**Pull request by anvit**
Adding language data files for all of the 2-letter languages that were available in the CLDR but were missing from symfony.

The script that I wrote for converting CLDR files to symfony can be found [here](https://github.com/artefactual-labs/cldr-data-convertor).

### CODE REVIEW

**Comment by anvit** [comment]
List of languages added:

Language code | Language
-- | --
bm | Bambara
bs | Bosnian
br | Breton
my | Burmese
ce | Chechen
dz | Dzongkha
ee | Ewe
ff | Fulah
lg | Ganda
ig | Igbo
ia | Interlingua
jv | Javanese
ks | Kashmiri
ki | Kikuyu
rw | Kinyarwanda
ky | Kirghiz
ku | Kurdish
lo | Lao
ln | Lingala
lu | Luba-Katanga
lb | Luxembourgish
mg | Malagasy
mi | Maori
mn | Mongolian
nd | North Ndebele
se | Northern Sami
os | Ossetic
qu | Quechua
rm | Rhaeto-Romance
rn | Rundi
sg | Sango
sa | Sanskrit
sc | Sardinian
gd | Scottish Gaelic
sn | Shona
sd | Sindhi
tg | Tajik
tt | Tatar
to | Tonga
tk | Turkmen
ug | Uighur
fy | Western Frisian
wo | Wolof
xh | Xhosa
yi | Yiddish
yo | Yoruba

**Comment by djjuhasz** [comment]
> The script that I wrote for converting CLDR files to symfony can be found [here](https://github.com/artefactual-labs/cldr-data-convertor).

Wow, this is awesome! Thanks @anvit. :clap:

**Review by djjuhasz — APPROVED** [review]
Looks good to me! :)

**Comment by anvit** [comment]
Also wanted to note that CLDR does have a lot of 3-letter language files that are currently missing in Symfony's i18n folder, but there still seems to be a bug preventing me from being able to add those in, which results in an out of memory error (once I remove the redirect in `languageAction.class.php` so that I could see what the exception was).
```
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 333451264 bytes) in /atom/src/apps/
qubit/modules/settings/actions/languageAction.class.php on line 45
```
I also wasn't able to add support for es_419 (Latin American Spanish), which also gave me the same error.

**Pull request merged**
