### PR TITLE
Dev/issue 11119 inventory clipboard

### PR DESCRIPTION
**Pull request by mcantelon**
* Add modifications to enable job creation by unauthenticated users
* Support clipboard export by unauthenticated users
* Persist alerts for each unauthenticated job
* Add ability for unauthenticated users to delete individual jobs
* Add class for managing an unauthenticated user's jobs

### CODE REVIEW

**Comment by mcantelon** [comment]
Seems adding this to the delete method of QubitJob might make sense:

```
if (isset($job->downloadPath))
{
  unlink($job->downloadPath);
}
```

EDIT: I ended up adding this to the PR.

**Comment by sbreker** [comment]
I did not pick these commits and test locally.  All looks good in terms of formatting I think.  Looking at the code I have a couple questions:

- The levels of description selector on the export page should be tested to ensure it still works if a user is unauthenticated.  I am unsure if it would be affected by this - the LOD filter does depend on ACL checks in the bg job.

- If I am understanding how this works correctly, the job id's are held in the user context in the unauthenticated user's browser I think?  If so, is there a danger that a malicious request could be created that could contain ANY job id for deletion?

**Comment by mcantelon** [comment]
Thanks Steve. Good call on the levels of description... will test. The job IDs, AFAIK, are only referenced server-side (except for the download file... I'll look at if I can obfuscate that).

**Comment by mcantelon** [comment]
I've added a commit message that's more detailed and added logic to obfuscate job IDs in job download filenames.

**Comment by sbreker** [comment]
Look good Mike!  👍

**Comment by MikeFE** [comment]
Hi guys, I wrote the original jobs system and if I recall (and could have outdated knowledge here), but QubitJob->delete() is primarily just called when you click 'clear jobs' in the job management page (will delete just job rows in the database for that particular user), or when you call the CLI task jobs:clear (will clear all the rows in the jobs table).

The original intention was just to let people remove cluttered job status lists where there can be hanging jobs stuck in 'running' due to technical issues or things like that. The intention wasn't to unlink the files generated from the jobs as well in the process.

I think this would be worth discussing esp. with Dan as well if this is the behavior you want. If it is, I think we should change the jobs:clear task and clear button in the jobs management page to inform the user it's going to delete the generated file too. Otherwise, I think we should create a separate method such as deleteJobFile() and use that instead when required, and not pack that behavior into the generic delete().

**Comment by MikeFE** [comment]
Actually, on second thought, we're using the db entries to let AtoM know where to point to the files anyway, so if those rows are gone the files are only seeable by someone with CLI access at that point. I'm less against this change now. 👍 

However, I feel like we should still warn users if files are about to be deleted.

**Comment by mcantelon** [comment]
Merged! I'll look into adding a confirmation before deletion warning of file deletion.

**Pull request closed without merging**
