### PR TITLE
arDominionBS5Plugin: add basicInfo collapse to accession/index

### PR DESCRIPTION
**Pull request by sevein**

### CODE REVIEW

**Review by jraddaoui — APPROVED** [review]
LGTM but I'd love @replaceafill's opinion, since he fixed those sections and added that row ;)

**Review by replaceafill — APPROVED** [review]
LGTM too. Thanks @sevein!

**Comment by jraddaoui** [comment]
Actually merged in 284d287, check those remotes @sevein!

**Comment by sevein** [comment]
I merged using GitHub's squash button 🤣

**Pull request merged**
