### PR TITLE
Setup Varnish in Docker environment, refs #11556

### PR DESCRIPTION
**Pull request by jraddaoui**
Extend Docker Compose environment with a Varnish container. Use a read
only volume for a basic configuration file to point to the Nginx
container and cache all (removing cookies and adding X-Cache headers).

### CODE REVIEW

**Comment by jraddaoui** [comment]
Hi @mcantelon, you may find this useful to test the language issue with Varnish ;)

**Comment by jraddaoui** [comment]
See also https://github.com/artefactual/atom-docs/pull/159

**Comment by mcantelon** [comment]
@jraddaoui Very handy... I'll test it out!

**Review by mcantelon — APPROVED** [review]
Very handy and works like a charm! Once you merge to qa/2.x I'll rebase my PR so I can add to the VCL.

**Comment by jraddaoui** [comment]
Thanks @mcantelon, done!

**Pull request merged**
