### PR TITLE
#5094 - bioghist: banish <chronlist>

### PR DESCRIPTION
**Pull request by mistydemeo**
As proposed by Dan in ticket 5094, this eliminates AtoM's complex `<chronlist>` field when exporting EAD in favour of a simplified, more standard pair of non-nested `<bioghist>` and `<origination>` fields.

TODO:
- [x] Add a `@role` attribute to `<geogname>` elements in the event that they've been added in the events module, to distinguish from regular place access points

### CODE REVIEW

**Comment by mistydemeo** [comment]
Here's a sample from our test server as AtoM currently encodes it:

``` xml
          <bioghist id="md5-68496595011f99cef1b02604f78e07db" encodinganalog="1.7B">
      <chronlist>
        <chronitem>
          <date type="creation" normal="20000000/20140000">2000 - 2014</date>          <eventgrp>
            <event>
                                            <note><p>...</p></note>
                            <origination encodinganalog="1.7C">
                                                      <persname>Dudely Dude the Third</persname>
                                                                                    </origination>
                              <date type="existence">0 - 3999</date>
                          </event>
          </eventgrp>
        </chronitem>
      </chronlist>
    </bioghist>
```

And here's the sample with this commit applied:

``` xml
          <bioghist id="md5-2328b1c22e60cf4f8181a82beca22922" encodinganalog="3.2.2">
              <note><p>...</p></note>
                    <date type="existence">0 - 3999</date>
          </bioghist>

    <origination encodinganalog="3.2.1">
                        <persname>Dudely Dude the Third</persname>
                                  </origination>
```

**Comment by mistydemeo** [comment]
Set the `role` attribute on `geogname` to `creation`:

``` xml
<controlaccess>
  ...
  <geogname>England.</geogname>
  <geogname>France.</geogname>
  <geogname>Halifax (N.S.) </geogname>
  <geogname role="creation">France.</geogname>
</controlaccess>
```

@fiver-watson, does this provide enough information for what you wanted on reimport? Or should there be more here?

**Comment by fiver-watson** [comment]
I think this should be sufficient!

Dan Gillean, MAS, MLIS
AtoM Product Manager / Systems Analyst,
Artefactual Systems, Inc http://www.artefactual.com/.
604-527-2056
@accesstomemory https://twitter.com/accesstomemory

**Comment by mistydemeo** [comment]
Updated to replace the generic `creation` role with the actual term:

``` xml
<geogname>England.</geogname>
<geogname>France.</geogname>
<geogname>Halifax (N.S.) </geogname>
<geogname role="reproduction">France.</geogname>
```

**Pull request merged**
