### PR TITLE
Autocomplete delay override

### PR DESCRIPTION
**Pull request by seamus-oconnor**
The autocomplete.js code now checks for a data-autocomplete-delay attribute on the input element to override the default 1 second delay.

### CODE REVIEW

**Comment by seamus-oconnor** [comment]
The '+' casts the string type to an int @sevein. It could still be useful to allow a per autocomplete box override as needed. The current 1s delay would help with server load but allowing an specific override could be beneficial in some cases.

**Comment by sevein** [comment]
Nice trick. Can you be more explicit and use (int) casting?
Why do you want to decrease the delay for that specific field?

**Comment by seamus-oconnor** [comment]
@sevein I will update the PR.

Reducing the delay was a requirement from my client. They found the delay to be hurting usability for that particular field.

**Comment by sevein** [comment]
Oh, that's funny! When I asked you to cast it I was thinking really in the PHP (int) syntax. Thank you so much, will merge soon.

**Comment by seamus-oconnor** [comment]
It has been about a month @sevein did you forget about this PR?

**Comment by sevein** [comment]
Sorry for the delay. It's now in qa/2.1.x (old 2.x), fc05fe001f15d5be3a19eb6f478216b2fae51c91.

**Comment by sevein** [comment]
@seamus-oconnor btw @fiver-watson is waiting for you to send him the [contributor agreement](https://www.qubit-toolkit.org/wiki/Contribute_code): ([pdf form](https://www.qubit-toolkit.org/accesstomemory-contributor-agreement-2014.pdf))

**Pull request closed without merging**
