### PR TITLE
Improve event dates import from METS, refs #10341

### PR DESCRIPTION
**Pull request by jraddaoui**
- Save DC date value without modification in free text field.
- Do not add first month and/or day to Y, Y-MM and Y/MM dates. This
  change also affects the 'acquisitionDate' import in csvAccessionImportTask.
- Move parse date function to a fully static class and other clean-ups.
- Include qubitPaseDate unit test => `php symfony test:unit qubitParseDate`.

### CODE REVIEW

**Review by sevein — COMMENTED** [review]
Tests! 💯 

Not really suggesting you to change it because it already looks awesome but something that I've seen in other languages is to apply a data-driven approach as follows:

```php
foreach (array(
    array(
      'input' => '2018', 'expected' => '2018',
      'desc' => 'Only year date shouldn\'t be modified.'
    ),
    array(
      'input' => '769', 'expected' => '769',
      'desc' => 'Only year date under 1000 shouldn\'t be modified.'
    ),
    array(
      'input' => '2018-05', 'expected' => '2018-05',
      'desc' => 'Proper year and month date shouldn\'t be modified.'
    ),
    array(
      'input' => '2018-05-21 12:05:45', 'expected' => '2018-05-21',
      'desc' => 'Time should be removed from the date.'
    ),
    array(
      'input' => '2018-13', 'expected' => '2018-01-01',
      'desc' => 'Bad year and month date should be processed by PHP\'s date_parse and formatted.'
    ),
    array(
      'input' => '20181127', 'expected' => '2018-11-27',
      'desc' => 'Everything else should be processed by PHP\'s date_parse and formatted.'
    ),
    array(
      'input' => '2018/12/31', 'expected' => '2018-12-31',
      'desc' => 'Everything else should be processed by PHP\'s date_parse and formatted.'
    ),
    array(
      'input' => 'January 7, 1975', 'expected' => '1975-01-07',
      'desc' => 'Everything else should be processed by PHP\'s date_parse and formatted.'
    )
) as $testCase) {
    $t->is(QubitFlatfileImport::parseDate($testCase['input']), $testCase['expected'], $testCase['desc']);
}
```

It doesn't change the behaviour.

PHPUnit seems to provide a similar solution: https://phpunit.de/manual/3.7/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers.

**Comment by jraddaoui** [comment]
That looks nicer and easier to modify, will do, thanks @sevein!

**Comment by mcantelon** [comment]
Very nice... looks good to me!

**Comment by jraddaoui** [comment]
f87327c in stable/2.4.x

**Pull request merged**
