### PR TITLE
Automatically orient scaled images (#13606)

### PR DESCRIPTION
**Pull request by mcantelon**
Added option to ImageMagick convert tool to automatically orient scaled images.

### CODE REVIEW

**Comment by mcantelon** [comment]
My commit references an issue on the old issue server. Do I need to make an issue on GitHub then change the number to that?

**Review by anvit — APPROVED** [review]
Looks good! @mcantelon I don't think there's a need to make a new GitHub issue for that, but maybe change the commit to say ref#13606 (without parenthesis, like the old commit format) to avoid GitHub from trying to connect it to an issue here?

**Comment by fiver-watson** [comment]
FYI @mcantelon it is the reference image that is most often affected by this issue. Will this address possible rotation issues for both, or just the thumbnail?

**Comment by mcantelon** [comment]
@fiver-watson It should be for all scaling.

**Comment by mcantelon** [comment]
@anvit Thanks Anvit... good catch... I'll amend the commit message before merging!

**Pull request merged**
