### PR TITLE
Make Diacritics strings translatable. (1803)

### LINKED ISSUE #1803: Problem: Some strings are missing in the translations bar from the new Diacritics settings page
### Current Behavior

First reported via the user forum, [2024-04-24](https://groups.google.com/g/ica-atom-users/c/kB3YzkzpUhg/m/bNh-U5EHAQAJ)

**Steps to reproduce the behavior**

* Log into a 2.8.x AtoM instance as an administrator
* Navigate to Admin > Settings > Diacritics
* Using the Language menu, flip the user interface settings to another langauge (e.g. French)
* Open the Translation bar menu
* Review the elements on the page that are still in English / untranslated, and look for them in the Translation bar menu

## Error encountered

A  number of strings on the page do not appear to be translatable at the moment, such as: 

* `The maximum size of file uploads is 64 MB.`
* `Please rebuild the search index after uploading diacritics mappings.`
* `Choose File` and `No file chosen`

### Expected Behavior

All text strings should be available for translation in the translations bar

### Context and Notes

The string *is* present in the translations repo, but not seen in the built-in translations bar of AtoM GUI.

### Version used

qa/2.x Docker instance - AtoM settings page reads: 2.8.2 - 193

### Operating System and version

Ubuntu 20.04

### Default installation culture

en

### PHP version

PHP 7.4

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by melaniekung**

### CODE REVIEW

**Review by jraddaoui — COMMENTED** [review]
Apart from indentation, are there any functional changes in this PR @mel?

**Comment by melaniekung** [comment]
@jraddaoui no, but the identations were required to make that string translatable

**Comment by jraddaoui** [comment]
@melaniekung, do you know why? It's the first time I see this.

**Comment by melaniekung** [comment]
@jraddaoui, i'm sorry i didn't catch this earlier... i don't think there's an issue with the original code - if we log into translations repo, we can see that the string is present and ready for translations. the issue mentioned using the translations bar menu where the string is not present for translations. my PR included the wrong wording for the reindex msg (copied code from languages settings page, which was already a translated string in AtoM.

not sure if there's still an issue present on figuring out why that string isn't present in the translations bar menu?

**Pull request closed without merging**
