### PR TITLE
Fix taxonomy normalization task to update the search index for affected records.

### PR DESCRIPTION
**Pull request by jasonhildebrand**
This is the issue we encountered:
1. Rename an existing Place term A to be the same as another term B (to eliminate a duplicate or inconsistent term).
2. Run the taxonomy:normalize task.  One of duplicate terms is removed.
3. Now bring up the remaining term using Browse -> Places.  Search for the term and select.  
4. A listing of archival descriptions is shown where the term is used.  It should show all the records which were related to either of the terms A or B.  However, not all of them show up.  

(Running search:populate would resolve the issue, however it takes several hours to it is not ideal to run this frequently).

Instead we developed this fix in the taxonomy normalization task to reindex the affected
information object records.

### CODE REVIEW

**Comment by sbreker** [comment]
Hi Jason

This is a great enhancement to AtoM that we would love to incorporate. I've noticed however that you've issued the pull request against stable/2.2.x.  I wanted to ask you if you could update the pull request so that it is based on qa/2.4.x instead of stable/2.2.x?  

Our policy is to that pull requests for new features may only be made against our current quality assurance branch - in this case qa/2.4.x.  If a pull request is a bug fix then we accept pull requests:

- Against the current quality assurance branch (qa/2.4.x), if the bug is present in the qa branch.  If the bug also applies to the current stable branch, we will subsequently backport the fix to the current stable branch when possible.
- Against the current stable branch (stable/2.3.x), if the bug is present in the stable branch but not in the current qa branch.

New features are incorporated into the latest quality assurance branch (e.g. qa/2.4.x) so the new features can be thoroughly tested before integration into a 'stable' release and to prevent unnecessary changes to the stable release and minimize the chance of regressions.

Let us know if you have any questions!

**Comment by jasonhildebrand** [comment]
OK, I have rebased on qa/2.4.x.  All appears to be working well on my end.

**Comment by sbreker** [comment]
Looks great Jason - thank-you for performing that rebase!  Code review looks good too.

I have merged to qa/2.4.x - you can view the merged commit here: https://github.com/artefactual/atom/commit/43c94b9b4021c3c15905bb32acf6e6a3e0cb2dbd

I've also made a small update to the commit message to add a title.  We try to format our commit messages as:
<title <= 50 chars>
<blank line>
<commit message wrapping at 72 chars>

One additional comment for next time regarding code formatting: PHP control statements should be followed by a space between it and the opening parentheses: 
e.g.  foreach ($affected_objects...
...as opposed to no space as with a function or method call (e.g. myfunc($foo) ).

Thanks for your contribution! 
Steve

**Comment by sbreker** [comment]
Hi Jason

One small thing I missed commenting on earlier was another coding-standard item: for variables we use a camel-case naming convention, so $affected_objects should be $affectedObjects. I will update this in qa/2.4.x.

Thanks again!
Steve

**Comment by jasonhildebrand** [comment]
Thanks, Steve!

**Pull request closed without merging**
