### PR TITLE
Fix finding aid custom L.O.D. issues, refs #12707

### PR DESCRIPTION
**Pull request by mcantelon**
Fixed issue with finding aid generation where the name of custom
levels of description wouldn't be displayed.

### CODE REVIEW

**Review by djjuhasz — CHANGES_REQUESTED** [review]
Please see https://projects.artefactual.com/issues/12707 for feedback on this change.

**Comment by mcantelon** [comment]
I've updated this PR with, hopefully, a fix.

**Comment by djjuhasz** [comment]
@mcantelon the otherlevel value is correctly being displayed on the finding aid now, as well as the "level" values being rendered properly, so that's good. :)

There is still an issue with the display of "otherlevel" descriptions in the finding aid template though which I think will require some further discussion, as the "best" solution is not clear to me.  In the standard finding aid template file and item level descriptions are displayed as a simple table, e.g.
issue_12707_finding_aid_screenshot_2

The "otherlevel" descriptions though are being displayed more like a "Series" description, e.g. 
issue_12707_finding_aid_screenshot_1

In the case of a "box" I would expect the descriptions to be displayed in a table like the file/item table, but this is not necessarily the best solution for all "otherlevel" values. :-/

I can think of a few possible options for how to display "otherlevel" descriptions in the finding aid:

1. All custom levels of description (LODs) are displayed in a table like the file/item list
2. The display of the custom LODs is determined by their position in the descriptive hierarchy, e.g. custom LODs that are a child of a "Series" description are displayed in a table, but custom LODs that are children of a Fonds/collection are displayed like a "Series"
3. We add a UI to configure how custom LODs are displayed in a finding aid

Of the three options I prefer option 2 as the best compromise between work required and functionality.  I believe Option 3 would require sponsorship as it requires significantly more development work than the first two options.

@fiver-watson do you have an opinion on how to display the "otherlevel" custom LODs?

**Comment by fiver-watson** [comment]
I had thought we shelved this, but: of @djjuhasz 's 3 options, I agree that Option 3 would require sponsorship, and that Option 2 is the best compromise available to us. There will be no perfect implementation from the sounds of it - we can't know what levels a user may choose to create or how they will be used, but trying to add some logic based on hierarchy position should at least help address some common use cases.

**Comment by mcantelon** [comment]
I've updated the PR to implement option two. Let me know if further tweaking is needed.

**Comment by mcantelon** [comment]
(Note to self: update commit message before merging.)

**Review by djjuhasz — CHANGES_REQUESTED** [review]
Nope, still not working:
Finding-aid-box-list-2019-09-19

I think your XPath selector is wrong, a series is not normally an "archdesc" element (that's usually the Fonds or Collection).  A series is usually a c-level element (e.g. c, c01, c02).

**Comment by mcantelon** [comment]
Ah, true... nice catch... should be an easy fix.

**Comment by mcantelon** [comment]
I've updated to fix.

**Review by djjuhasz — APPROVED** [review]
Looks good @mcantelon!
finding_aid_boxes_c544bda

**Pull request merged**
